version: '3.8'

services:
  bonzi-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Optional: Add volume for development (uncomment for dev)
    # volumes:
    #   - .:/app
    #   - /app/node_modules